### ISSUE TITLE
M-x package-install<ret>slime-docker<ret> fails 

### ISSUE THREAD

**Issue by alanruttenberg** [daewok/slime-docker#1]
*messages* says: 

Contacting host: melpa.org:80
package-install-from-archive: http://melpa.org/packages/docker-tramp-20161020.2220.tar: Not found

FYI. I will checkout and try from source.

**Comment by daewok** [comment]
That looks like your package metadata is out of date. `package-list-packages` or `package-refresh-contents` should fix that I believe.

**Comment by alanruttenberg** [comment]
yes, that did it. Thanks!

**Comment by alanruttenberg** [comment]
Eh, minor problem - there's a dependency on slime that the package manager listens to overriding the slime I actually use. I'll figure some way to work around it, but consider it a soft-request that you submit a package that doesn't have the slime dependency.

**Comment by alanruttenberg** [comment]
Looks like it's fixed by an explicit load of slime-autoloads of my version - previously I used require, which was satisfied by the package installed version. Perhaps worth mentioning in the documentation.

Thanks a lot for slime-docker, BTW, it saved me lot of time!
